name: color_sort
description: "A fun and complicated color sorting game"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1           # State management
  audioplayers: ^6.4.0       # Sound effects
  flutter_animate: ^4.5.0    # Enhanced animations
  shared_preferences: ^2.2.2 # Local storage for game state
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
